import { documentationIds } from "../../constant";
import FacetParagraph from "../FacetParagraph"

export default () => {

    const preCodeValue = `
    <Head>
        <script src="https://api.facet.run/js?id={ID}"></script>
        <title>...</title>
        <link rel="icon" href="/favicon.ico" />
    </Head>
    `;

    return <>
        <h1 style={{ fontFamily: "Helvetica", fontSize: "27px", fontWeight: 600 }} id={documentationIds.oneLineCodeIntegration}>Integration</h1>
        <FacetParagraph color={"#5D5D5D"}  >
            Copy the snippet of code generated by the facet extension and displayed at the top of the extension. This will give you the single line of code that you need to paste into your head HTML code. The ID refers to the ID of your website. Once this line of code is integrated in your system, you should be able to see the configurations applied from the facet extension.
            <pre><code>
                {preCodeValue}
            </code></pre>
        Note that you would need to embed the script tag as early as your application loads, to ensure correct DOM dismissal before the elements are loaded on the page.
    </FacetParagraph>
    </>
}